CREATE TABLE nav_hist(
no INT(20) unsigned NOT NULL AUTO_INCREMENT,
pno INT(11) unsigned NOT NULL,
uno INT(11) unsigned NOT NULL,
longitude DOUBLE NOT NULL,
latitude DOUBLE NOT NULL,
time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
type CHAR(1) NOT NULL DEFAULT 'N',
PRIMARY KEY(no),
FOREIGN KEY (pno) REFERENCES parent (no),
FOREIGN KEY (uno) REFERENCES user (no)
);
