CREATE TABLE user_location(
no INT(20) unsigned NOT NULL AUTO_INCREMENT,
time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
uno INT(11) unsigned NOT NULL,
longitude DOUBLE NOT NULL,
latitude DOUBLE NOT NULL,
PRIMARY KEY (no),
FOREIGN KEY (uno) REFERENCES user (no)
);
